name: Actualizar Datos Históricos

on:
  schedule:
    - cron: '0 6 * * *'  # Ejecutar todos los días a las 6:00 UTC
  workflow_dispatch:     # Permite ejecución manual desde GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de descarga
        run: |
          python src/mi_proyecto/run_collector.py

      - name: Confirmar cambios y hacer push (si hay nuevos datos)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Actualización automática de datos históricos" || echo "Sin cambios"
          git push
